server:
  port: 8080
  context-path: /router-filter-demo
  session:
    timeout: 3600
#  ssl:
#    enabled: true
#    keyStore: classpath:certificate/x.p12
#    keyStoreType: pkcs12
#    keyStorePassword: x
#    keyPassword: x
#    clientAuth: need
#    trustStore: classpath:certificate/x.jks
#    trustStoreType: jks
#    trustStorePassword: x


logging:
  level:
    root: INFO


zuul:
  ssl-hostname-validation-enabled: false
  sensitive-headers: